programas ejemplos/mastodon-master/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations', authorized_applications: 'oauth/authorized_applications'
  end

  get '.well-known/host-meta', to: 'xrd#host_meta', as: :host_meta
  get '.well-known/webfinger', to: 'xrd#webfinger', as: :webfinger

  devise_for :users, path: 'auth', controllers: {
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  get '/users/:username', to: redirect('/@%{username}'), constraints: { format: :html }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show] do
      member do
        get :embed
      end
    end

    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    member do
      get :followers
      get :following

      post :follow
      post :unfollow
    end
  end

  get '/@:username', to: 'accounts#show', as: :short_account
  get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :preferences, only: [:show, :update]
    resource :import, only: [:show, :create]

    resource :export, only: [:show] do
      collection do
        get :follows, to: 'exports#download_following_list'
        get :blocks, to: 'exports#download_blocking_list'
      end
    end

    resource :two_factor_auth, only: [:show] do
      member do
        post :enable
        post :disable
      end
    end
  end

  resources :media, only: [:show]
  resources :tags,  only: [:show]

  # Remote follow
  get  :authorize_follow, to: 'authorize_follow#new'
  post :authorize_follow, to: 'authorize_follow#create'

  namespace :admin do
    resources :pubsubhubbub, only: [:index]
    resources :domain_blocks, only: [:index, :new, :create]
    resources :settings, only: [:index, :update]

    resources :reports, only: [:index, :show] do
      member do
        post :resolve
        post :silence
        post :suspend
        post :remove
      end
    end

    resources :accounts, only: [:index, :show] do
      member do
        post :silence
        post :unsilence
        post :suspend
        post :unsuspend
      end
    end
  end

  get '/admin', to: redirect('/admin/settings', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        member do
          get :context
          get :card
          get :reblogged_by
          get :favourited_by

          post :reblog
          post :unreblog
          post :favourite
          post :unfavourite
        end
      end

      get '/timelines/home',     to: 'timelines#home', as: :home_timeline
      get '/timelines/public',   to: 'timelines#public', as: :public_timeline
      get '/timelines/tag/:id',  to: 'timelines#tag', as: :hashtag_timeline

      get '/search', to: 'search#index', as: :search

      resources :follows,    only: [:create]
      resources :media,      only: [:create]
      resources :apps,       only: [:create]
      resources :blocks,     only: [:index]
      resources :mutes,      only: [:index]
      resources :favourites, only: [:index]
      resources :reports,    only: [:index, :create]

      resource :instance, only: [:show]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
        end
      end

      resources :accounts, only: [:show] do
        collection do
          get :relationships
          get :verify_credentials
          get :search
        end

        member do
          get :statuses
          get :followers
          get :following

          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end
      end
    end

    namespace :web do
      resource :settings, only: [:update]
    end
  end

  get '/web/(*any)', to: 'home#index', as: :web

  get '/about',      to: 'about#index'
  get '/about/more', to: 'about#more'
  get '/terms',      to: 'about#terms'

  root 'home#index'

  match '*unmatched_route', via: :all, to: 'application#raise_not_found'
end

programas ejemplos/mastodon-master/app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  layout 'public'

  before_action :set_account
  before_action :set_link_headers
  before_action :authenticate_user!, only: [:follow, :unfollow]
  before_action :check_account_suspension

  def show
    respond_to do |format|
      format.html do
        @statuses = @account.statuses.permitted_for(@account, current_account).order('id desc').paginate_by_max_id(20, params[:max_id], params[:since_id])
        @statuses = cache_collection(@statuses, Status)
      end

      format.atom do
        @entries = @account.stream_entries.order('id desc').where(hidden: false).with_includes.paginate_by_max_id(20, params[:max_id], params[:since_id])
        render xml: AtomSerializer.render(AtomSerializer.new.feed(@account, @entries.to_a))
      end

      format.activitystreams2
    end
  end

  def follow
    FollowService.new.call(current_user.account, @account.acct)
    redirect_to account_path(@account)
  end

  def unfollow
    UnfollowService.new.call(current_user.account, @account)
    redirect_to account_path(@account)
  end

  def followers
    @followers = @account.followers.order('follows.created_at desc').paginate(page: params[:page], per_page: 12)
  end

  def following
    @following = @account.following.order('follows.created_at desc').paginate(page: params[:page], per_page: 12)
  end

  private

  def set_account
    @account = Account.find_local!(params[:username])
  end

  def set_link_headers
    response.headers['Link'] = LinkHeader.new([[webfinger_account_url, [%w(rel lrdd), %w(type application/xrd+xml)]], [account_url(@account, format: 'atom'), [%w(rel alternate), %w(type application/atom+xml)]]])
  end

  def webfinger_account_url
    webfinger_url(resource: "acct:#{@account.acct}@#{Rails.configuration.x.local_domain}")
  end

  def check_account_suspension
    gone if @account.suspended?
  end
end

programas ejemplos/mastodon-master/app/controllers/admin/accounts_controller.rb
# frozen_string_literal: true

class Admin::AccountsController < ApplicationController
  before_action :require_admin!
  before_action :set_account, except: :index

  layout 'admin'

  def index
    @accounts = Account.alphabetic.paginate(page: params[:page], per_page: 40)

    @accounts = @accounts.local                             if params[:local].present?
    @accounts = @accounts.remote                            if params[:remote].present?
    @accounts = @accounts.where(domain: params[:by_domain]) if params[:by_domain].present?
    @accounts = @accounts.silenced                          if params[:silenced].present?
    @accounts = @accounts.recent                            if params[:recent].present?
    @accounts = @accounts.suspended                         if params[:suspended].present?
  end

  def show; end

  def suspend
    Admin::SuspensionWorker.perform_async(@account.id)
    redirect_to admin_accounts_path
  end

  def unsuspend
    @account.update(suspended: false)
    redirect_to admin_accounts_path
  end

  def silence
    @account.update(silenced: true)
    redirect_to admin_accounts_path
  end

  def unsilence
    @account.update(silenced: false)
    redirect_to admin_accounts_path
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:silenced, :suspended)
  end
end

programas ejemplos/mastodon-master/app/controllers/api/v1/accounts_controller.rb
# frozen_string_literal: true

class Api::V1::AccountsController < ApiController
  before_action -> { doorkeeper_authorize! :read }, except: [:follow, :unfollow, :block, :unblock, :mute, :unmute]
  before_action -> { doorkeeper_authorize! :follow }, only: [:follow, :unfollow, :block, :unblock, :mute, :unmute]
  before_action :require_user!, except: [:show, :following, :followers, :statuses]
  before_action :set_account, except: [:verify_credentials, :suggestions, :search]

  respond_to :json

  def show; end

  def verify_credentials
    @account = current_user.account
    render action: :show
  end

  def following
    results   = Follow.where(account: @account).paginate_by_max_id(limit_param(DEFAULT_ACCOUNTS_LIMIT), params[:max_id], params[:since_id])
    accounts  = Account.where(id: results.map(&:target_account_id)).map { |a| [a.id, a] }.to_h
    @accounts = results.map { |f| accounts[f.target_account_id] }

    # set_account_counters_maps(@accounts)

    next_path = following_api_v1_account_url(max_id: results.last.id)    if results.size == limit_param(DEFAULT_ACCOUNTS_LIMIT)
    prev_path = following_api_v1_account_url(since_id: results.first.id) unless results.empty?

    set_pagination_headers(next_path, prev_path)

    render action: :index
  end

  def followers
    results   = Follow.where(target_account: @account).paginate_by_max_id(limit_param(DEFAULT_ACCOUNTS_LIMIT), params[:max_id], params[:since_id])
    accounts  = Account.where(id: results.map(&:account_id)).map { |a| [a.id, a] }.to_h
    @accounts = results.map { |f| accounts[f.account_id] }

    # set_account_counters_maps(@accounts)

    next_path = followers_api_v1_account_url(max_id: results.last.id)    if results.size == limit_param(DEFAULT_ACCOUNTS_LIMIT)
    prev_path = followers_api_v1_account_url(since_id: results.first.id) unless results.empty?

    set_pagination_headers(next_path, prev_path)

    render action: :index
  end

  def statuses
    @statuses = @account.statuses.permitted_for(@account, current_account).paginate_by_max_id(limit_param(DEFAULT_STATUSES_LIMIT), params[:max_id], params[:since_id])
    @statuses = @statuses.where(id: MediaAttachment.where(account: @account).where.not(status_id: nil).reorder('').select('distinct status_id')) if params[:only_media]
    @statuses = @statuses.without_replies if params[:exclude_replies]
    @statuses = cache_collection(@statuses, Status)

    set_maps(@statuses)
    # set_counters_maps(@statuses)
    # set_account_counters_maps(@statuses.flat_map { |s| [s.account, s.reblog? ? s.reblog.account : nil] }.compact.uniq)

    next_path = statuses_api_v1_account_url(max_id: @statuses.last.id)    unless @statuses.empty?
    prev_path = statuses_api_v1_account_url(since_id: @statuses.first.id) unless @statuses.empty?

    set_pagination_headers(next_path, prev_path)
  end

  def follow
    FollowService.new.call(current_user.account, @account.acct)
    set_relationship
    render action: :relationship
  end

  def block
    BlockService.new.call(current_user.account, @account)

    @following   = { @account.id => false }
    @followed_by = { @account.id => false }
    @blocking    = { @account.id => true }
    @requested   = { @account.id => false }
    @muting      = { @account.id => current_user.account.muting?(@account.id) }

    render action: :relationship
  end

  def mute
    MuteService.new.call(current_user.account, @account)
    set_relationship
    render action: :relationship
  end

  def unfollow
    UnfollowService.new.call(current_user.account, @account)
    set_relationship
    render action: :relationship
  end

  def unblock
    UnblockService.new.call(current_user.account, @account)
    set_relationship
    render action: :relationship
  end

  def unmute
    UnmuteService.new.call(current_user.account, @account)
    set_relationship
    render action: :relationship
  end

  def relationships
    ids = params[:id].is_a?(Enumerable) ? params[:id].map(&:to_i) : [params[:id].to_i]

    @accounts    = Account.where(id: ids).select('id')
    @following   = Account.following_map(ids, current_user.account_id)
    @followed_by = Account.followed_by_map(ids, current_user.account_id)
    @blocking    = Account.blocking_map(ids, current_user.account_id)
    @muting      = Account.muting_map(ids, current_user.account_id)
    @requested   = Account.requested_map(ids, current_user.account_id)
  end

  def search
    @accounts = AccountSearchService.new.call(params[:q], limit_param(DEFAULT_ACCOUNTS_LIMIT), params[:resolve] == 'true', current_account)

    # set_account_counters_maps(@accounts) unless @accounts.nil?

    render action: :index
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def set_relationship
    @following   = Account.following_map([@account.id], current_user.account_id)
    @followed_by = Account.followed_by_map([@account.id], current_user.account_id)
    @blocking    = Account.blocking_map([@account.id], current_user.account_id)
    @muting      = Account.muting_map([@account.id], current_user.account_id)
    @requested   = Account.requested_map([@account.id], current_user.account_id)
  end
end

programas ejemplos/mastodon-master/app/helpers/accounts_helper.rb
# frozen_string_literal: true

module AccountsHelper
  def pagination_options
    {
      previous_label: safe_join([fa_icon('chevron-left'), t('pagination.prev')], ' '),
      next_label: safe_join([t('pagination.next'), fa_icon('chevron-right')], ' '),
      inner_window: 1,
      outer_window: 0,
    }
  end
end

programas ejemplos/mastodon-master/app/helpers/admin/accounts_helper.rb
# frozen_string_literal: true

module Admin::AccountsHelper
  def filter_params(more_params)
    params.permit(:local, :remote, :by_domain, :silenced, :suspended, :recent).merge(more_params)
  end

  def filter_link_to(text, more_params)
    link_to text, filter_params(more_params), class: params.merge(more_params).compact == params.compact ? 'selected' : ''
  end

  def table_link_to(icon, text, path, options = {})
    link_to safe_join([fa_icon(icon), text]), path, options.merge(class: 'table-action-link')
  end
end

programas ejemplos/mastodon-master/app/views/accounts/_grid_card.html.haml
.account-grid-card
  .account-grid-card__header
    .avatar= image_tag account.avatar.url(:original)
    .name
      = link_to TagManager.instance.url_for(account) do
        %span.display_name.emojify= display_name(account)
        %span.username= "@#{account.acct}"
  %p.note.emojify= truncate(strip_tags(account.note), length: 150)

programas ejemplos/mastodon-master/app/views/accounts/_header.html.haml
.card.h-card.p-author{ style: "background-image: url(#{@account.header.url( :original)})" }
  - if user_signed_in? && current_account.id != @account.id && !current_account.requested?(@account)
    .controls
      - if current_account.following?(@account)
        = link_to t('accounts.unfollow'), unfollow_account_path(@account), data: { method: :post }, class: 'button'
      - else
        = link_to t('accounts.follow'), follow_account_path(@account), data: { method: :post }, class: 'button'
  - elsif !user_signed_in?
    .controls
      .remote-follow
        = link_to t('accounts.remote_follow'), account_remote_follow_path(@account), class: 'button'
  .avatar= image_tag @account.avatar.url(:original), class: 'u-photo'
  %h1.name
    %span.p-name.emojify= display_name(@account)
    %small
      %span.p-nickname= "@#{@account.username}"
      = fa_icon('lock') if @account.locked?
  .details
    .bio
      .account__header__content.p-note.emojify= Formatter.instance.simplified_format(@account)

    .details-counters
      .counter{ class: active_nav_class(short_account_url(@account)) }
        = link_to short_account_url(@account), class: 'u-url u-uid' do
          %span.counter-label= t('accounts.posts')
          %span.counter-number= number_with_delimiter @account.statuses_count
      .counter{ class: active_nav_class(following_account_url(@account)) }
        = link_to following_account_url(@account) do
          %span.counter-label= t('accounts.following')
          %span.counter-number= number_with_delimiter @account.following_count
      .counter{ class: active_nav_class(followers_account_url(@account)) }
        = link_to followers_account_url(@account) do
          %span.counter-label= t('accounts.followers')
          %span.counter-number= number_with_delimiter @account.followers_count

programas ejemplos/mastodon-master/app/views/accounts/_nothing_here.html.haml
%p.nothing-here= t('accounts.nothing_here')

programas ejemplos/mastodon-master/app/views/accounts/followers.html.haml
- content_for :page_title do
  = t('accounts.people_who_follow', name: display_name(@account))

= render partial: 'header'

.accounts-grid
  - if @followers.empty?
    = render partial: 'nothing_here'
  - else
    = render partial: 'grid_card', collection: @followers, as: :account, cached: true

= will_paginate @followers, pagination_options

programas ejemplos/mastodon-master/app/views/accounts/following.html.haml
- content_for :page_title do
  = t('accounts.people_followed_by', name: display_name(@account))

= render partial: 'header'

.accounts-grid
  - if @following.empty?
    = render partial: 'nothing_here'
  - else
    = render partial: 'grid_card', collection: @following, as: :account, cached: true

= will_paginate @following, pagination_options

programas ejemplos/mastodon-master/app/views/accounts/show.html.haml
- content_for :page_title do
  = display_name(@account)

- content_for :header_tags do
  %link{ rel: 'salmon', href: api_salmon_url(@account.id) }/
  %link{ rel: 'alternate', type: 'application/atom+xml', href: account_url(@account, format: 'atom') }/

  %meta{ property: 'og:site_name', content: site_title }/
  %meta{ property: 'og:type', content: 'profile' }/
  %meta{ property: 'og:title', content: "#{@account.username} on #{Rails.configuration.x.local_domain}" }/
  %meta{ property: 'og:description', content: @account.note }/
  %meta{ property: 'og:image', content: full_asset_url(@account.avatar.url(:original)) }/
  %meta{ property: 'og:image:width', content: '120' }/
  %meta{ property: 'og:image:height', content: '120' }/
  %meta{ property: 'twitter:card', content: 'summary' }/

- if !user_signed_in? && !Rails.configuration.x.single_user_mode
  = render partial: 'shared/landing_strip', locals: { account: @account }

.h-feed
  %data.p-name{ value: "#{@account.username} on #{Rails.configuration.x.local_domain}" }/

  = render partial: 'header'

  - if @statuses.empty?
    .accounts-grid
      = render partial: 'nothing_here'
  - else
    .activity-stream
      = render partial: 'stream_entries/status', collection: @statuses, as: :status

  .pagination
    - if @statuses.size == 20
      = link_to safe_join([t('pagination.next'), fa_icon('chevron-right')], ' '), short_account_url(@account, max_id: @statuses.last.id), class: 'next_page', rel: 'next'