programas ejemplos/mastodon-master/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations', authorized_applications: 'oauth/authorized_applications'
  end

  get '.well-known/host-meta', to: 'xrd#host_meta', as: :host_meta
  get '.well-known/webfinger', to: 'xrd#webfinger', as: :webfinger

  devise_for :users, path: 'auth', controllers: {
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  get '/users/:username', to: redirect('/@%{username}'), constraints: { format: :html }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show] do
      member do
        get :embed
      end
    end

    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    member do
      get :followers
      get :following

      post :follow
      post :unfollow
    end
  end

  get '/@:username', to: 'accounts#show', as: :short_account
  get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :preferences, only: [:show, :update]
    resource :import, only: [:show, :create]

    resource :export, only: [:show] do
      collection do
        get :follows, to: 'exports#download_following_list'
        get :blocks, to: 'exports#download_blocking_list'
      end
    end

    resource :two_factor_auth, only: [:show] do
      member do
        post :enable
        post :disable
      end
    end
  end

  resources :media, only: [:show]
  resources :tags,  only: [:show]

  # Remote follow
  get  :authorize_follow, to: 'authorize_follow#new'
  post :authorize_follow, to: 'authorize_follow#create'

  namespace :admin do
    resources :pubsubhubbub, only: [:index]
    resources :domain_blocks, only: [:index, :new, :create]
    resources :settings, only: [:index, :update]

    resources :reports, only: [:index, :show] do
      member do
        post :resolve
        post :silence
        post :suspend
        post :remove
      end
    end

    resources :accounts, only: [:index, :show] do
      member do
        post :silence
        post :unsilence
        post :suspend
        post :unsuspend
      end
    end
  end

  get '/admin', to: redirect('/admin/settings', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        member do
          get :context
          get :card
          get :reblogged_by
          get :favourited_by

          post :reblog
          post :unreblog
          post :favourite
          post :unfavourite
        end
      end

      get '/timelines/home',     to: 'timelines#home', as: :home_timeline
      get '/timelines/public',   to: 'timelines#public', as: :public_timeline
      get '/timelines/tag/:id',  to: 'timelines#tag', as: :hashtag_timeline

      get '/search', to: 'search#index', as: :search

      resources :follows,    only: [:create]
      resources :media,      only: [:create]
      resources :apps,       only: [:create]
      resources :blocks,     only: [:index]
      resources :mutes,      only: [:index]
      resources :favourites, only: [:index]
      resources :reports,    only: [:index, :create]

      resource :instance, only: [:show]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
        end
      end

      resources :accounts, only: [:show] do
        collection do
          get :relationships
          get :verify_credentials
          get :search
        end

        member do
          get :statuses
          get :followers
          get :following

          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end
      end
    end

    namespace :web do
      resource :settings, only: [:update]
    end
  end

  get '/web/(*any)', to: 'home#index', as: :web

  get '/about',      to: 'about#index'
  get '/about/more', to: 'about#more'
  get '/terms',      to: 'about#terms'

  root 'home#index'

  match '*unmatched_route', via: :all, to: 'application#raise_not_found'
end

programas ejemplos/mastodon-master/app/models/stream_entry.rb
# frozen_string_literal: true

class StreamEntry < ApplicationRecord
  include Paginable

  belongs_to :account, inverse_of: :stream_entries
  belongs_to :activity, polymorphic: true
  belongs_to :status, foreign_type: 'Status', foreign_key: 'activity_id', inverse_of: :stream_entry

  validates :account, :activity, presence: true

  STATUS_INCLUDES = [:account, :stream_entry, :media_attachments, :tags, mentions: :account, reblog: [:stream_entry, :account, :media_attachments, :tags, mentions: :account], thread: [:stream_entry, :account]].freeze

  default_scope { where(activity_type: 'Status') }
  scope :with_includes, -> { includes(:account, status: STATUS_INCLUDES) }

  def object_type
    orphaned? || targeted? ? :activity : status.object_type
  end

  def verb
    orphaned? ? :delete : status.verb
  end

  def targeted?
    [:follow, :request_friend, :authorize, :reject, :unfollow, :block, :unblock, :share, :favorite].include? verb
  end

  def target
    orphaned? ? nil : status.target
  end

  def title
    orphaned? ? nil : status.title
  end

  def content
    orphaned? ? nil : status.content
  end

  def threaded?
    (verb == :favorite || object_type == :comment) && !thread.nil?
  end

  def thread
    orphaned? ? nil : status.thread
  end

  def mentions
    orphaned? ? [] : status.mentions.map(&:account)
  end

  private

  def orphaned?
    status.nil?
  end
end

programas ejemplos/mastodon-master/app/controllers/stream_entries_controller.rb
# frozen_string_literal: true

class StreamEntriesController < ApplicationController
  layout 'public'

  before_action :set_account
  before_action :set_stream_entry
  before_action :set_link_headers
  before_action :check_account_suspension

  def show
    respond_to do |format|
      format.html do
        return gone if @stream_entry.activity.nil?

        if @stream_entry.activity_type == 'Status'
          @ancestors   = @stream_entry.activity.reply? ? cache_collection(@stream_entry.activity.ancestors(current_account), Status) : []
          @descendants = cache_collection(@stream_entry.activity.descendants(current_account), Status)
        end
      end

      format.atom do
        render xml: AtomSerializer.render(AtomSerializer.new.entry(@stream_entry, true))
      end
    end
  end

  def embed
    response.headers['X-Frame-Options'] = 'ALLOWALL'
    @external_links = true

    return gone if @stream_entry.activity.nil?

    render layout: 'embedded'
  end

  private

  def set_account
    @account = Account.find_local!(params[:account_username])
  end

  def set_link_headers
    response.headers['Link'] = LinkHeader.new([[account_stream_entry_url(@account, @stream_entry, format: 'atom'), [%w(rel alternate), %w(type application/atom+xml)]]])
  end

  def set_stream_entry
    @stream_entry = @account.stream_entries.where(activity_type: 'Status').find(params[:id])
    @type         = @stream_entry.activity_type.downcase

    raise ActiveRecord::RecordNotFound if @stream_entry.activity.nil? || (@stream_entry.hidden? && (@stream_entry.activity_type != 'Status' || (@stream_entry.activity_type == 'Status' && !@stream_entry.activity.permitted?(current_account))))
  end

  def check_account_suspension
    gone if @account.suspended?
  end
end

programas ejemplos/mastodon-master/app/helpers/stream_entries_helper.rb
# frozen_string_literal: true

module StreamEntriesHelper
  def display_name(account)
    account.display_name.blank? ? account.username : account.display_name
  end

  def acct(account)
    "@#{account.acct}#{@external_links && account.local? ? "@#{Rails.configuration.x.local_domain}" : ''}"
  end

  def avatar_for_status_url(status)
    status.reblog? ? status.reblog.account.avatar.url(:original) : status.account.avatar.url(:original)
  end

  def entry_classes(status, is_predecessor, is_successor, include_threads)
    classes = ['entry']
    classes << 'entry-reblog u-repost-of h-cite' if status.reblog?
    classes << 'entry-predecessor u-in-reply-to h-cite' if is_predecessor
    classes << 'entry-successor u-comment h-cite' if is_successor
    classes << 'entry-center h-entry' if include_threads
    classes.join(' ')
  end

  def relative_time(date)
    date < 5.days.ago ? date.strftime('%d.%m.%Y') : "#{time_ago_in_words(date)} ago"
  end

  def reblogged_by_me_class(status)
    user_signed_in? && @reblogged.key?(status.id) ? 'reblogged' : ''
  end

  def favourited_by_me_class(status)
    user_signed_in? && @favourited.key?(status.id) ? 'favourited' : ''
  end

  def rtl?(text)
    return false if text.empty?

    matches = /[\p{Hebrew}|\p{Arabic}|\p{Syriac}|\p{Thaana}|\p{Nko}]+/m.match(text)

    return false unless matches

    rtl_size = matches.to_a.reduce(0) { |acc, elem| acc + elem.size }.to_f
    ltr_size = text.strip.size.to_f

    rtl_size / ltr_size > 0.3
  end
end

programas ejemplos/mastodon-master/app/views/stream_entries/_content_spoiler.html.haml
.media-spoiler
  %span= t('stream_entries.sensitive_content')
  %span= t('stream_entries.click_to_show')

programas ejemplos/mastodon-master/app/views/stream_entries/_detailed_status.html.haml
.detailed-status.light
  = link_to TagManager.instance.url_for(status.account), class: 'detailed-status__display-name p-author h-card', target: @external_links ? '_blank' : nil, rel: 'noopener' do
    %div
      %div.avatar
        = image_tag status.account.avatar.url(:original), width: 48, height: 48, alt: '', class: 'u-photo'
    %span.display-name
      %strong.p-name.emojify= display_name(status.account)
      %span.p-nickname= acct(status.account)

  .status__content.e-content.p-name.emojify<
    - unless status.spoiler_text.blank?
      %p{ style: 'margin-bottom: 0' }<
        %span>= "#{status.spoiler_text} "
        %a.status__content__spoiler-link{ href: '#' }= t('statuses.show_more')
    %div{ style: "display: #{status.spoiler_text.blank? ? 'block' : 'none'}; direction: #{rtl?(status.content) ? 'rtl' : 'ltr'}" }= Formatter.instance.format(status)

  - unless status.media_attachments.empty?
    - if status.media_attachments.first.video?
      .video-player
        - if status.sensitive?
          = render partial: 'stream_entries/content_spoiler'
        %video{ src: status.media_attachments.first.file.url(:original), loop: true, class: 'u-video' }
    - else
      .detailed-status__attachments
        - if status.sensitive?
          = render partial: 'stream_entries/content_spoiler'
        .status__attachments__inner
          - status.media_attachments.each do |media|
            = render partial: 'stream_entries/media', locals: { media: media }

  %div.detailed-status__meta
    %data.dt-published{ value: status.created_at.to_time.iso8601 }
    = link_to TagManager.instance.url_for(status), class: 'detailed-status__datetime u-url u-uid', target: @external_links ? '_blank' : nil, rel: 'noopener' do
      %span= l(status.created_at)
    ·
    - if status.application
      - if status.application.website.blank?
        %strong.detailed-status__application= status.application.name
      - else
        = link_to status.application.name, status.application.website, class: 'detailed-status__application', target: '_blank', rel: 'noopener'
      ·
    %span<
      = fa_icon('retweet')
      %span= status.reblogs_count
    ·
    %span<
      = fa_icon('star')
      %span= status.favourites_count

    - if user_signed_in?
      ·
      = link_to t('statuses.open_in_web'), web_url("statuses/#{status.id}"), class: 'open-in-web-link'

programas ejemplos/mastodon-master/app/views/stream_entries/_media.html.haml
.media-item
  = link_to media.remote_url.blank? ? media.file.url(:original) : media.remote_url, style: media.image? ? "background-image: url(#{media.file.url(:original)})" : "", target: '_blank', rel: 'noopener', class: "u-#{media.video? || media.gifv? ? 'video' : 'photo'}" do
    - unless media.image?
      %video{ src: media.file.url(:original), autoplay: true, loop: true }/

programas ejemplos/mastodon-master/app/views/stream_entries/_simple_status.html.haml
.status.light
  .status__header
    .status__meta
      = link_to time_ago_in_words(status.created_at), TagManager.instance.url_for(status), class: 'status__relative-time u-url u-uid', title: l(status.created_at), target: @external_links ? '_blank' : nil, rel: 'noopener'
      %data.dt-published{ value: status.created_at.to_time.iso8601 }

    = link_to TagManager.instance.url_for(status.account), class: 'status__display-name p-author h-card', target: @external_links ? '_blank' : nil, rel: 'noopener' do
      .status__avatar
        %div
          = image_tag status.account.avatar(:original), width: 48, height: 48, alt: '', class: 'u-photo'
      %span.display-name
        %strong.p-name.emojify= display_name(status.account)
        %span.p-nickname= acct(status.account)

  .status__content.e-content.p-name.emojify<
    - unless status.spoiler_text.blank?
      %p{ style: 'margin-bottom: 0' }<
        %span>= "#{status.spoiler_text} "
        %a.status__content__spoiler-link{ href: '#' }= t('statuses.show_more')
    %div{ style: "display: #{status.spoiler_text.blank? ? 'block' : 'none'}; direction: #{rtl?(status.content) ? 'rtl' : 'ltr'}" }= Formatter.instance.format(status)

  - unless status.media_attachments.empty?
    .status__attachments
      - if status.sensitive?
        = render partial: 'stream_entries/content_spoiler'
      - if status.media_attachments.first.video?
        .status__attachments__inner
          .video-item
            = link_to (status.media_attachments.first.remote_url.blank? ? status.media_attachments.first.file.url(:original) : status.media_attachments.first.remote_url), style: "background-image: url(#{status.media_attachments.first.file.url(:small)})", target: '_blank', rel: 'noopener', class: 'u-video' do
              .video-item__play
                = fa_icon('play')
      - else
        .status__attachments__inner
          - status.media_attachments.each do |media|
            = render partial: 'stream_entries/media', locals: { media: media }

programas ejemplos/mastodon-master/app/views/stream_entries/_status.html.haml
- include_threads ||= false
- is_predecessor  ||= false
- is_successor    ||= false
- centered        ||= include_threads && !is_predecessor && !is_successor

- if status.reply? && include_threads
  = render partial: 'stream_entries/status', collection: @ancestors, as: :status, locals: { is_predecessor: true }

.entry{ class: entry_classes(status, is_predecessor, is_successor, include_threads) }
  - if status.reblog?
    .pre-header
      %div.pre-header__icon
        = fa_icon('retweet fw')
      %span
        = link_to TagManager.instance.url_for(status.account), class: 'status__display-name muted' do
          %strong= display_name(status.account)
        = t('stream_entries.reblogged')

  = render partial: centered ? 'stream_entries/detailed_status' : 'stream_entries/simple_status', locals: { status: status.proper }

- if include_threads
  = render partial: 'stream_entries/status', collection: @descendants, as: :status, locals: { is_successor: true }

programas ejemplos/mastodon-master/app/views/stream_entries/embed.html.haml
.activity-stream.activity-stream-headless
  = render partial: @type, locals: { @type.to_sym => @stream_entry.activity, centered: true }

programas ejemplos/mastodon-master/app/views/stream_entries/show.html.haml
- content_for :header_tags do
  %link{ rel: 'alternate', type: 'application/atom+xml', href: account_stream_entry_url(@account, @stream_entry, format: 'atom') }/
  %link{ rel: 'alternate', type: 'application/json+oembed', href: api_oembed_url(url: account_stream_entry_url(@account, @stream_entry), format: 'json') }/

  %meta{ property: 'og:site_name', content: site_title }/
  %meta{ property: 'og:type', content: 'article' }/
  %meta{ property: 'og:title', content: "#{@account.username} on #{Rails.configuration.x.local_domain}" }/

  - if @stream_entry.activity.is_a?(Status) && !@stream_entry.activity.spoiler_text.blank?
    %meta{ property: 'og:description', content: @stream_entry.activity.spoiler_text }/
  - else
    %meta{ property: 'og:description', content: @stream_entry.activity.content }/

  - if @stream_entry.activity.is_a?(Status) && @stream_entry.activity.media_attachments.size > 0
    %meta{ property: 'og:image', content: full_asset_url(@stream_entry.activity.media_attachments.first.file.url(:small)) }/
  - else
    %meta{ property: 'og:image', content: full_asset_url(@account.avatar.url(:original)) }/
    %meta{ property: 'og:image:width', content: '120' }/
    %meta{ property: 'og:image:height', content: '120' }/

  %meta{ property: 'twitter:card', content: 'summary' }/

- if !user_signed_in? && !Rails.configuration.x.single_user_mode
  = render partial: 'shared/landing_strip', locals: { account: @stream_entry.account }

.activity-stream.activity-stream-headless
  = render partial: "stream_entries/#{@type}", locals: { @type.to_sym => @stream_entry.activity, include_threads: true }